### ISSUE TITLE
Shadow Problem  /  影の問題

### ISSUE THREAD

**Issue by leikal** [pennennennennennenem/sdPBR#1]
![Shadow](https://user-images.githubusercontent.com/85371379/125200754-434c8180-e23a-11eb-9f62-2d189c0d2fec.png)

Hi, first say that SDPBR is great and I thank you for distributing it.

I have a shadow problem as shown in the picture. Is there any way to fix it? Tried changing it with SDPBR's shadow parameter, but it basically doesn't change much.

I know there are effects like Perfect Shadows, but that means replacing the shaders with those effects.

Greetings and thanks

こんにちは、最初にSDPBRは素晴らしいと言ってください、そして私はそれを配布してくれてありがとう。

写真のように影の問題があります。それを修正する方法はありますか？ SDPBRのシャドウパラメータで変更してみましたが、基本的にはあまり変わりません。

パーフェクトシャドウのようなエフェクトがあることは知っていますが、それはシェーダーをそれらのエフェクトに置き換えることを意味します。

**Comment by pennennennennennenem** [comment]
ご報告ありがとうございます😃
意図的にノイズを加える事で影が極端にブロック状になる事を抑えているので、ある程度ノイズが出るケースはあると思います
影の作り方は平行光源(MMDの照明操作パネルで作られる物)と追加ライト(sdPBR/lightingフォルダに入っている物)では少し異なりますので、各々試してみて具合の良い方を使ってみてください
また、sdPBR.pmxや追加ライトのpmxのパラメータだけでなく、sdPBRConfig.exeでシャドウマップの解像度を変えることが出来ます
助けになれば幸いです

Thank you for your report😃.
I've intentionally added noise to keep the shadows from becoming extremely blocky, so there will be some cases where noise will appear.
The way to create shadows is a little different between directional light (created in MMD's lighting control panel) and additional lights (in the sdPBR/lighting folder), so please try each one and use the one that works best for you.
Also, you can change the resolution of the shadow maps with sdPBRConfig.exe as well as the parameters of sdPBR.pmx and the pmx of the additional lights.
Hope this helps!

**Comment by pennennennennennenem** [comment]
Version 3.40でシャドウマップを改善しました
以前よりノイズが目立たないように調整することができると思います

Shadow maps have been improved in Version 3.40！
Noise can be adjusted to be less noticeable than before.
