### ISSUE TITLE
[Request] English version of sdPBRconfig and hdr2skybox

### ISSUE THREAD

**Issue by NathanDreamweaver** [pennennennennennenem/sdPBR#2]
Hello,
It would be very nice to have an english version.
Even machine translated would be better than nothing

**Comment by pennennennennennenem** [comment]
Thanks! sorry I haven't read it in a while.
The next version(Ver. 4.50), each tool will have an English caption!

**Comment by NathanDreamweaver** [comment]
Thank you!!
